homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation/', views.confirmation, name="confirmation"),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Status(models.Model):
	name = models.CharField('name', max_length=100)
	status = models.CharField('status', max_length=100)
	
	def __str__(self):
		return self.name

homepage/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    
	class Meta:
		model = Status
		fields = ['name', 'status']
		labels = {'name': 'Name', 'status': 'Status'}
		
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.Meta.fields:
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
			})

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Status
from . import forms
from .forms import StatusForm

# Create your views here.
def index(request):
	stats = Status.objects.all().values()
	if (request.method == 'POST'):
		form = StatusForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect('/')
	else:
		form = StatusForm()
	return render(request, 'index.html', {'stats': stats, 'form':form})

def confirmation(request):
	if request.method == 'POST':
		statusForm = StatusForm(request.POST)  
		if statusForm.is_valid():
			name = statusForm.data['name']
			status = statusForm.data['status']
			confirmForm = StatusForm(initial={'name': name, 'status': status})
			return render(request, 'confirmation.html', {'confirmForm': confirmForm, 'confirmName': name, 'confirmStatus': status}) 
		else:
			response = redirect('/')
			return response
	if request.method == "GET":
		return redirect('/')

homepage/templates/confirmation.html
<!doctype html>
{% load static %}
<html lang="en"><head>
  <title>Confirmation Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Open Sans" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body class="confirmationBody">
	
	<div class="row">
		<h1 class="title">Confirmation Page</h1>
		<div class="rectangle"></div>
    </div>

    <form action="/" method="POST">
        {% csrf_token %}
        <p id="confirmation">Are you sure your name is <strong>{{ confirmName }}</strong> and your status is <strong>{{ confirmStatus }}</strong>?</p>
        <div class="hidden">
            {% for fields in confirmForm %}
                {{ fields }}
            {% endfor %}
        </div>
        <input type='submit' value="Yes" id="id_yes">
    </form>
    <button onclick="javascript:history.back()" id="id_no">No</button>
   
    
	<!--test-->
</body>
<script>

</script>
</html>

homepage/templates/index.html
<!doctype html>
{% load static %}
<html lang="en"><head>
  <title>Story 7</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Open Sans" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
	
	<div class="row">
		<h1 class="title">Hello, how are you?</h1>
		<div class="rectangle"></div>
	</div>
	
	<div class="row" style="padding-left:5vw; padding-right:5vw;">
		<form action="confirmation/" method = 'POST'>
			{% csrf_token %}
			<div class="form-row">
				<div class="col-sm-1" style="text-align: right; line-height: 25px;">
					<p>name:</p>
					<p>status:</p>
				</div>
				<div class="form-group col-sm-11"> 
					<div class="textfield" style="width: 400px;"> 
						{% for fields in form %}
							{{ fields }}
						{% endfor %}
					</div>              
				</div>
			</div>
			<div class="row">
				<input type="submit" class="btn submit" value="Submit" id="id_submit">
			</div>
			<br><br>
			<div>
				<div class="col-md-12">
					<div>
						<p id="status">Status</p>
						<p> 
							{% for a in stats %}
							<div class="statusbox">
								<div class="row">
									<div class="col-sm-6">
										<p id="id_name"> {{ a.name }}</p>
									</div>
									<div class="col-sm-6">
										<p id="id_status"> {{ a.status }}</p>
									</div>
								</div>  
							</div>
							<br> 
							{% endfor %}
						</p>               
					</div>
				</div>
			</div>
	   </form>
	   <button onclick="change()" name ='change' id="id_changeColor">Change Colour</button>
	</div>

	<!--test-->
</body>
<script>
	function change() {
		var x = document.getElementsByClassName('statusbox');
		var i;
		for(i = 0; i < x.length; i++) {
		x[i].style.color = 'black';
		}
	}
</script>
</html>